### ISSUE TITLE
Example notebook

### ISSUE THREAD

**Issue by blogeman** [AllenInstitute/drcme#11]
This looks like a great set of tools and I am excited to try them out. Is there an example notebook somewhere to help get started? I tried looking for one on the Allen Brain Atlas SDK website but couldn't find anything implementing the scripts from drcme. Any suggestions for how to get started would be appreciated. Thanks.

**Comment by blogeman** [comment]
The Open Science Week at the Allen Institute got me thinking about this repository again. I would love to run this package first with Allen Institute data and then with my own, but don't know where to start. If anyone reads this could you please show me an example of how to use this toolset?

**Comment by gouwens** [comment]
I've now added documentation, along with some simple examples in the Getting Started section. Please check it out here: https://drcme.readthedocs.io/en/latest/ and feel free to submit feedback if sections aren't clear.
