### ISSUE TITLE
Issues with current version of marshmallow that is installed with argschema

### ISSUE THREAD

**Issue by smestern** [AllenInstitute/drcme#8]
It seems that the argschema is incompatible with the current version of marshmallow. Therefore inputs to the 'run' scripts throw an error.   
`File "C:\Users\SMest\Anaconda3\lib\site-packages\marshmallow\schema.py", line 1216, in _invoke_processors
    data = processor(data, many=many, **kwargs)
TypeError: make_object() got an unexpected keyword argument 'many'`
After some testing I found the versions that work with the DRCME project.
Short of changing argschema itself, a quick fix appears to be freezing marshmallow @ 2.20.5
and argschema @ 1.17.5
`argschema==1.17.5`
`marshmallow==2.20.5`

**Comment by gouwens** [comment]
I've changed the requirements until argschema is updated for the newest marshmallow.
